# Generated by Django 3.2.3 on 2021-05-17 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.TextField(blank=True, verbose_name='Тема сообщения')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст сообщения')),
                ('id_template', models.ForeignKey(db_column='id_template', null=True, on_delete=django.db.models.deletion.SET_NULL, to='template.templates')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='ValueVariable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, verbose_name='Полное описание назначения переменной')),
                ('id_message', models.ForeignKey(db_column='id_message', null=True, on_delete=django.db.models.deletion.SET_NULL, to='message.message')),
            ],
            options={
                'db_table': 'value_variables',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Время создания сообщения')),
                ('send', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки сообщения')),
                ('email', models.CharField(max_length=254, verbose_name='Адрес электронной почты')),
                ('id_message', models.ForeignKey(db_column='id_message', null=True, on_delete=django.db.models.deletion.SET_NULL, to='message.message')),
            ],
            options={
                'db_table': 'recipients',
            },
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, verbose_name='Описание ошибки')),
                ('id_message', models.ForeignKey(db_column='id_message', null=True, on_delete=django.db.models.deletion.SET_NULL, to='message.message')),
            ],
            options={
                'db_table': 'errors',
            },
        ),
    ]
