# Generated by Django 3.2.3 on 2021-05-17 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Полное описание шаблона')),
                ('html', models.TextField(verbose_name='Шаблон в формате html с ключевыми словами в {}')),
            ],
            options={
                'db_table': 'templates',
            },
        ),
        migrations.CreateModel(
            name='BaseVariables',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='Название переменной в шаблоне, которое будет заключено в {}')),
                ('description', models.TextField(blank=True, verbose_name='Описание назначения переменной')),
                ('id_template', models.ForeignKey(db_column='id_template', null=True, on_delete=django.db.models.deletion.SET_NULL, to='template.templates')),
            ],
            options={
                'db_table': 'base_variables',
            },
        ),
    ]
